# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

collections:
  - name: ansible.posix
  - name: inwx.collection
    source: https://github.com/inwx/ansible-collection.git
    type: git
    version: 1.3.1
