# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

collections:
  - name: ansible.posix
    version: 1.6.2
  - name: kubernetes.core
    version: 5.0.0
  - name: inwx.collection
    source: https://github.com/inwx/ansible-collection.git
    type: git
    version: 1.3.1
