# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

---
- name: "Configure DNS records"
  hosts: "{{ hostlist | default('localhost') }}"
  connection: local
  become: false
  gather_facts: false

  vars_files:
    - vault.yml

  tasks:
    - name: "Create earth.xlii.cc A Record"
      inwx.collection.dns:
        domain: xlii.cc
        record: earth
        type: A
        value: 5.104.107.120
        ttl: 300
        username: "{{ vault_dns_user }}"
        password: "{{ vault_dns_pass }}"
        state: present
    - name: "Create earth.xlii.cc AAAA Record"
      inwx.collection.dns:
        domain: xlii.cc
        record: earth
        type: AAAA
        ttl: 300
        value: "2001:4ba0:cafe:cc4::1"
        username: "{{ vault_dns_user }}"
        password: "{{ vault_dns_pass }}"
        state: present
...
