# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

---
- name: Install k3sup and Bootstrap or Update K3s
  hosts: "{{ hostlist | default('all, !localhost') }}"
  become: false
  gather_facts: true

  roles:
    - { role: vandot.k3sup, become: true }

  tasks:
    - name: Bootstrap or Update K3s  # noqa: no-changed-when
      ansible.builtin.command:
        argv:
          - /usr/local/bin/k3sup
          - install
          - --local
          - --k3s-version=v1.31.2+k3s1
          - "--host={{ inventory_hostname }}"
          - "--ip={{ ansible_default_ipv4.address }}"
...
