# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

---
- name: Install or Update Rancher
  hosts: "{{ hostlist | default('all, !localhost') }}"
  become: false
  gather_facts: false

  vars:
    kubeconfig: ~/kubeconfig

  tasks:
    - name: Install Python dependencies
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        name:
          - python3-yaml
          - python3-kubernetes
        state: present
      become: true

    - name: Add jetstack chart repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Deploy cert-manager chart
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: v1.16.1
        release_namespace: cert-manager
        create_namespace: true
        wait: true
        update_repo_cache: true
        kubeconfig: "{{ kubeconfig }}"
        state: present
        values:
          crds:
            enabled: true

    - name: Create cattle-system namespace
      kubernetes.core.k8s:
        name: cattle-system
        api_version: v1
        kind: Namespace
        kubeconfig: "{{ kubeconfig }}"
        state: present

    - name: Create secret tls-ca from files/isrgrootx1.pem
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: tls-ca
            namespace: cattle-system
          data:
            cacerts.pem: "{{ lookup('file', 'files/isrgrootx1.pem') | ansible.builtin.b64encode }}"

    - name: Add rancher-stable chart repo
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "https://releases.rancher.com/server-charts/stable"

    - name: Deploy rancher chart
      kubernetes.core.helm:
        name: rancher
        chart_ref: rancher-stable/rancher
        chart_version: v2.9.3
        release_namespace: cattle-system
        wait: true
        update_repo_cache: true
        kubeconfig: "{{ kubeconfig }}"
        state: present
        values:
          crds:
            enabled: true
          hostname: earth.xlii.cc
          ingress:
            tls:
              source: letsEncrypt
          letsEncrypt:
            email: dominik@wombacher.cc
            ingress:
              class: traefik
            environment: production
          privateCA: true
          replicas: 1
          agentTLSMode: strict

    - name: Add turtles chart repo
      kubernetes.core.helm_repository:
        name: turtles
        repo_url: "https://rancher.github.io/turtles"

    - name: Deploy rancher-turtles chart
      kubernetes.core.helm:
        name: rancher-turtles
        chart_ref: turtles/rancher-turtles
        chart_version: v0.13.0
        release_namespace: rancher-turtles-system
        create_namespace: true
        wait: true
        update_repo_cache: true
        kubeconfig: "{{ kubeconfig }}"
        state: present
...
