# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

---
- name: Entrypoint to run all playbooks
  hosts: all
  become: false
  gather_facts: false
  no_log: true

- name: Import DNS playbook
  import_playbook: dns.yml

- name: Import K3sup playbook
  import_playbook: k3sup.yml

- name: Import Rancher playbook
  import_playbook: k3sup.yml
...
